hoodapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('neighbourhood.urls')),
    
]

neighbourhood/urls.py
from django.urls import path,include,re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'neighbourhood'

urlpatterns=[
    path('',views.index, name = 'index'),
    path('search/', views.search_results, name='search_results'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logoutUser, name='logout'),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('hood/', views.hood, name='hood'),
    path('hooddetails/<int:hood_id>', views.hooddetails, name='hooddetails'),
    path('newHood/', views.newHood, name='newHood'),
    path('business/', views.business, name='business'),

]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

neighbourhood/models.py
import email
from django.db import models
from django.contrib.auth.models import User
from unicodedata import name
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from cloudinary.models import CloudinaryField
import datetime as dt
# Create your models here.
class Neighbourhood(models.Model):
    name=models.CharField(max_length=50, blank=True)
    location =models.CharField(max_length=50, blank=True)
    image = CloudinaryField('image')
    description = models.TextField(max_length=1000, null=True)
    occupants_count = models.IntegerField(default=0)
    admin = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def _str_(self):
        return self.name
    def create_neighbourhood(self):
        self.save()

    def delete_neighbourhood(self):
        self.delete()

    @classmethod
    def find_neighbourhood(cls, id):
        return cls.objects.filter(id=id)
    @classmethod
    def update_neighbourhood(cls, id ,name):
        return cls.objects.filter(id=id).update()


class Profile(models.Model):
     name=models.CharField(max_length=50, blank=True)
     email=models.EmailField(max_length=50, blank=True)
     user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="Profile",null=True)
     location =models.CharField(max_length=50, blank=True)
     neighbourhood_name =  models.CharField(max_length=50, blank=True)
     house=models.CharField(max_length=50, blank=True)
     def __str__(self):
        return self.name

     @receiver(post_save, sender=User)
     def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

   #   @receiver(post_save, sender=User)
   #   def save_user_profile(sender, instance, **kwargs):
   #      instance.save()

     def save_profile(self):
        self.user

     def delete_profile(self):
        self.delete()

     def __str__(self):
        return self.user.username


     @classmethod
     def search_profile(cls, name):
        return cls.objects.filter(user__username__icontains=name).all()

     def __str__(self):
        return f'{self.user.username} Profile'

class Post(models.Model):
    title=models.CharField(max_length=30, blank=True)
    post = models.TextField()
    date= models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(Profile,on_delete=models.CASCADE,related_name="owner")
    hood = models.ForeignKey(Neighbourhood,on_delete=models.CASCADE,related_name="post")

    def __str__(self):
        return self.title

    @classmethod
    def search_project_name(cls, search_term):
        return cls.objects.filter(
        title__icontains=search_term)
        

class Business(models.Model):
     name=models.CharField(max_length=50, blank=True)
     user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,related_name='owner')   
     location =models.CharField(max_length=50, blank=True)
     contact = models.IntegerField(default=0, blank=True)
     image = CloudinaryField('image')
     neighbourhood = models.ForeignKey(Neighbourhood,on_delete=models.SET_NULL, null=True,related_name='business',blank=True)
     email=models.EmailField(max_length=50, blank=True)


     def __str__(self):
        return f'{self.user.username} Business'

     def create_business(self):
        self.save()

     def delete_business(self):
        self.delete()

neighbourhood/forms.py
# from django.forms import ModelForm
from .models import Neighbourhood, Profile,Post,Business
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(forms.ModelForm):

    first_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional')
    email = forms.EmailField(max_length=300, help_text='Enter a valid email address')
    password1 = forms.CharField(max_length=20, widget=forms.PasswordInput,required=True)
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput,required=True)

    class Meta:
        model = User
        fields = [
            'username', 
            'first_name', 
            'last_name', 
            'email', 
            'password1', 
            'password2', 
        ]

class UpdateUserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'name', 
            'location', 
            'email',
            'neighbourhood_name',
            'house',
        ]
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',  
        ]
class newHoodForm(forms.ModelForm):
    class Meta:
        model = Neighbourhood
        fields = [
            'image',
            'name',
            'description',
            'location',
            'occupants_count',
        ]

class BusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        fields = [
            'name',            
            'location',
            'email',
            'contact',
        ]

neighbourhood/views.py
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm, UpdateUserProfileForm, newHoodForm,BusinessForm
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.models import User
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib import messages
from .models import Post,Neighbourhood,Profile,Business 
from pickle import FALSE
from django.http import HttpResponse, Http404
from django.core.exceptions import ObjectDoesNotExist


from . import models
import neighbourhood
# Create your views here.
def SignUp(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = SignUpForm()
    return render(request, 'django_registration/registration_form.html', {'form': form})

def loginrequest(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("/index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request, "register/login.html", {"loginform": form})

@login_required(login_url='/accounts/login')
def index(request):
    posts = Neighbourhood.objects.all()
    return render(request, 'index.html',{'posts':posts})

@login_required(login_url='/accounts/login/')
def profile(request):
    current_user = request.user
    profileForm = UpdateUserProfileForm()
    if request.method == 'POST':
        profileForm = UpdateUserProfileForm(request.POST, request.FILES)
        if profileForm.is_valid():
            profile=profileForm.save(commit=FALSE)
            profile.user = current_user
            profile.save()
        else:
            profileForm = UpdateUserProfileForm()
        profile = Profile.get.all()
    return render(request,'profile.html',{'current_user':current_user,'profileForm':profileForm,'profile':profile})

def logoutUser(request):
 logout(request)
 return redirect(index)

@login_required(login_url='/accounts/login')
def search_results(request):

    if 'search_username' in request.GET and request.GET["search_username"]:
        search_term = request.GET.get("search_username")
        searched_username = Profile.search_profile(search_term)
        message = f"{search_term}"

        return render(request, 'search.html',{"message":message, 'profile':searched_username})
    else:
        message = "You haven't searched for any term"
        return render(request, 'search.html',{"message":message})

def hood(request):
    try:
            hoods = Neighbourhood.objects.all()
    except ObjectDoesNotExist:
        raise Http404()
    return render(request, 'hood.html', {'hoods':hoods,})

def hooddetails(request,hood_id):
    try:
        hood = Neighbourhood.objects.get(id=hood_id)
    except ObjectDoesNotExist:
        raise Http404()
    business = Business.objects.all()
    return render(request, 'hooddets.html', {'hood': hood,'business':business})

@login_required(login_url='login')
def business(request):
    current_user = request.user
    if request.method == 'POST':
        form = BusinessForm(request.POST, request.FILES)
        if form.is_valid():
           form = form.save(commit=False)
           form.user = current_user
           form.save()
        return redirect('neighbourhood:hooddetails')
    else:
        form = BusinessForm()

    return render(request, 'business.html',{'form':form})

@login_required(login_url='/accounts/login')
def newHood(request):  
    if request.method == 'POST':
        form = newHoodForm(request.POST, request.FILES)
        if form.is_valid():
            hood= form.save(commit=False)
            hood.admin = request.user
            hood.save() 
            return redirect('neighbourhood:hood')
    else:
        form = newHoodForm()

    return render(request, 'newhood.html', {"form": form})

neighbourhood/templates/business.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block styles %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@300&family=Roboto:wght@300&display=swap" rel="stylesheet">
   
{% endblock%}
{% block content %}
<div class="container">
    <form  action="{% url 'neighbourhood:business'%}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {% bootstrap_form form %}
            <input type="submit" class="btn btn-outline-secondary btn-center" value="Upload " >
    </form>

</div>
<style>
    .container{
        margin-top: 60px;
        font-family: 'Roboto', sans-serif;
    }
</style>
{% endblock %}

neighbourhood/templates/hood.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block styles %}
{% load static %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@300&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
{% endblock%}
{% block content %}
<div class="backg">
  <div class="overlay">
<div class="container-fluid">
  <div class="enclose">
    <div class="navbar  sticky-top" role="navigation">
      <div class="container-fluid upper">
        
          <div class="navbar-header">
             <h1>
              <a class="navbar-brand" href="{% url 'neighbourhood:index' %}"> THEE HOOD</a>
            </div>
             </h1>
        <div class="list">

     <form class="navbar-form" role="search" action="{% url 'neighbourhood:search_results' %}">
            <div class="input-group">
              <div class="search">
              
              <a href="{% url 'neighbourhood:index' %}">
                
                <input  id="search_input" type="text"  placeholder="Search business..." >
                <i class="fa fa-search" style="font-size:12px"></i>
                <label  value="submit" for="search-input"><span class="glyphicon glyphicon-search search-icon"></span></label>
            
              </a>
            </div>
                </div>
            </div>
     </form>
         
          <div class="home-icon">
                <a href="{% url 'neighbourhood:index' %}">
                  <h1> </h1>
                  <i class="fa fa-home" style="font-size:22px"></i>
                </a>
              
              </div>
         </div>
              
              <div class="dropdown">
                <div class="dropd">
                <a href="#" class="dropdown-toggle btn btn-default" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                  <i id="greyi" class="fa fa-user" style="font-size:22px"></i>
                          <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li>
                    <img src="" alt="image">
                  </li>
                  <li>
                    <a class="drop" href="{%url 'neighbourhood:profile'%}">Profile</a>
                  </li>
                 
                  <li>
                    <a class="drop" href="/accounts/logout">Logout</a>
                  </li>
                </ul>
              </li>
            </div>
           
          </div> 
      
          <div class="form-group">
            <a href="{% url 'neighbourhood:newHood' %}">
              <input class="btn btn-secondary" id="add_input" type="submit" value="New Hood"  placeholder="Add New Hood" >
            </a>

          </div>
           
<div class="container-fluid">
    <div class="container-xl">
     <div class="row ">
        {% for hood in hoods %}
       <div class="col-md-4">
        <div class="inside mx-5 ">
        <div class="card my-4" style="width: 26rem;height: 26rem ;" >

           <div class="header">
            <h5 class="card-title">
                {{hood.name}} <br>
                {{hood.location}} 
            </h5>
           </div>
    
              <img id="image" class="card-img" src="{{hood.image.url}}" alt="image" width="210px" height="210px">
           
            <p class="card-text">
                {{hood.description}} <br>
              Total number of Occupants:  {{hood.occupants_count}} <br>

            </p>
            <div class="card-body">
                <a href="{% url 'neighbourhood:hooddetails' hood.id %}">
                    <button type="button" class="btn btn-info">
                        View Hood Details
                      </button>
                 </a> 
          </div>
           

        </div>

    </div>
        </div>
          {% endfor %}
 
       </div>
    </div>
     
       </div>
     </div>
    </div>
   

    <style>
          *{
           
           padding: 0px;
           margin: 0px;
       }
      
       .navbar-header a{
       color: white;
       font-size: 25px;
       }
       .enclose{
           display: flex;
           flex-direction: column;
          
       }
       .upper{
         width: 660px;
         height: 40px;
         color: white;
       }
       .card{
           color: black;
           margin: 0px;
           border: none;
           padding-bottom: 0px;
           transition: all .3s;
           margin-right: 180px;
       }
       .card:hover{
         transform: scale(1.04);
       }
       .glyphicon{
         color: white;
       }
       .backg{
       height: 1100px;
       background-image: url(/media/images/hood1.jpeg);
       background-size: cover;
       background-position: center;
       background-repeat: no-repeat;
         
       }
       .overlay{
         background: rgb(0, 0, 0, .8);
         height:100vh;
       }
       .post{
       background-color: aqua;
       }

     #search_input{
       background-color: rgb(250, 246, 246);
       border: none;

     }
     #add_input{
       background-color: rgb(248, 248, 248);
       color: rgb(170, 169, 169);
       width: 110px;
       height: 160%;
       margin-top: 16px;
     }
    .dropd{
      padding-top: 15px;
      margin-right: 8px;
     color: white;
    }
     .dropd a{
       color: white;
     }
   
     .row{
         margin-top: 100px;
     }
     .card-text{
        text-align: center;
     }
     .header h5{
         text-align: center;
     }
     .form-group btn{
       color: black;
     }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

    {% endblock %}

neighbourhood/templates/hooddets.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block styles %}
{% load static %}
{{form.media}}
{% bootstrap_css %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@300&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
{% endblock%}
{% block content %}
<div class="backg">
  <div class="overlay">
<div class="container-fluid">
  <div class="enclose">
    <div class="navbar  sticky-top" role="navigation">
      <div class="container-fluid upper">
        
          <div class="navbar-header">
             <h1>
              <a class="navbar-brand" href="{% url 'neighbourhood:index' %}"> THEE HOOD</a>
            </div>
             </h1>
        <div class="list">

     <form class="navbar-form" role="search" action="{% url 'neighbourhood:search_results' %}">
            <div class="input-group">
              <div class="search">
              
              <a href="{% url 'neighbourhood:index' %}">
                
                <input  id="search_input" type="text"  placeholder="Search business..." >
                <i class="fa fa-search" style="font-size:12px"></i>
                <label  value="submit" for="search-input"><span class="glyphicon glyphicon-search search-icon"></span></label>
            
              </a>
            </div>
                </div>
            </div>
     </form>
         
          <div class="home-icon">
                <a href="{% url 'neighbourhood:index' %}">
                  <h1> </h1>
                  <i class="fa fa-home" style="font-size:22px"></i>
                </a>
              
              </div>
         </div>
              
              <div class="dropdown">
                <div class="dropd">
                <a href="#" class="dropdown-toggle btn btn-default" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                  <i id="greyi" class="fa fa-user" style="font-size:22px"></i>
                          <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li>
                    <img src="" alt="image">
                  </li>
                  <li>
                    <a class="drop" href="{%url 'neighbourhood:profile'%}">Profile</a>
                  </li>
                 
                  <li>
                    <a class="drop" href="/accounts/logout">Logout</a>
                  </li>
                </ul>
              </li>
            </div>
           
          </div> 
          <div class="form-group" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="">
            <a href="{% url 'neighbourhood:business'%}">
              <input class="btn btn-secondary" id="add_input" type="submit"  value="Add Business" placeholder="Add New business" >
            </a>

          </div>
         
    </div>
</div>
           
</div>
<div class="container-fluid">
    <div class="container-xl">
     <div class="row ">
      
       <div class="">
        <div class="inside  ">
        <div class="card my-4" style="width: 55rem;height: 45rem ;" >

           <div class="header">
            <h5 class="card-title">
                {{hood.name}} <br>
                {{hood.location}} 
                
            </h5>
           </div>
    
              <img id="image" class="card-img" src="{{hood.image.url}}" alt="image" width="320px" height="380px">
           
            <p class="card-text">
                {{hood.description}} <br>
              Total number of Occupants:  {{hood.occupants_count}} <br>
              <div class="bus">
                <h4>List of Businesses</h4>
             
                {% for busi in business %}
                {{busi.name}} <br>
          {% endfor %}
          <button type="button" class="btn btn-info">
            Join Hood 
          </button>
          <button type="button" class="btn btn-info">
            Leave Hood 
          </button>
              </div>
            
            </p>
            <div class="card-body">
               
          </div>
           
        </div>

    </div>
        </div>
        
       </div>
    </div>
</div>
</div>
<div class="container-xl">
    <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
 <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
       <h5 class="modal-title" id="exampleModalLabel">New Business</h5>
       <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
     </div>
     <div class="modal-body">
      
     </div>
     <div class="modal-footer">
       <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
       <button type="button" class="btn btn-primary">Save changes</button>
     </div>
   </div>
 </div>
</div> 

 </div>
<style>
    *{
       
        padding: 0px;
        margin: 0px;
        color: black;
    }
   
    .navbar-header a{
    color: rgb(19, 18, 18);
    font-size: 25px;
    }
    .enclose{
        display: flex;
        flex-direction: column;
       
    }
    .upper{
      width: 660px;
      height: 40px;
    }
    .card{
        margin: 0px;
        border: none;
        padding-bottom: 0px;
        
    }
   
    .glyphicon{
      color: white;
    }
    .backg{
    height: 1100px;
   background-color: rgb(178, 179, 179);
      
    }
    .overlay{
      background: rgb(0, 0, 0, .4);
      height:100vh;
    }
    .post{
    background-color: aqua;
    }

  #search_input{
    background-color: rgb(250, 246, 246);
    border: none;

  }
  #add_input{
    background-color: rgb(248, 248, 248);
    color: rgb(170, 169, 169);
    width: 110px;
    height: 160%;
    margin-top: 16px;
  }
 .dropd{
   padding-top: 15px;
   margin-right: 8px;
  color: white;
 }
  .dropd a{
    color: white;
  }
  .row{
         margin-top: 50px;
         margin-left: 210px;
     }
     .card-text{
        text-align: center;
     }
     .bus{
        text-align: center;
     }
     .header h5{
         text-align: center;
     }
  
</style>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}

neighbourhood/templates/index.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block styles %}
{% load static %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@300&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
{% endblock%}
{% block content %}
<div class="backg">
  <div class="overlay">
<div class="container-fluid">
  <div class="enclose">
    <div class="navbar  sticky-top" role="navigation">
      <div class="container-fluid upper">
        
          <div class="navbar-header">
             <h1>
              <a class="navbar-brand" href="{% url 'neighbourhood:index' %}"> THEE HOOD</a>
            </div>
             </h1>
        <div class="list">

     <form class="navbar-form" role="search" action="{% url 'neighbourhood:search_results' %}">
            <div class="input-group">
              <div class="search">
              
              <a href="{% url 'neighbourhood:index' %}">
                
                <input  id="search_input" type="text"  placeholder="Search business..." >
                <i class="fa fa-search" style="font-size:12px"></i>
                <label  value="submit" for="search-input"><span class="glyphicon glyphicon-search search-icon"></span></label>
            
              </a>
            </div>
                </div>
            </div>
     </form>
         
          <div class="home-icon">
                <a href="{% url 'neighbourhood:index' %}">
                  <h1> </h1>
                  <i id="greyi" class="fa fa-home" style="font-size:22px"></i>
                </a>
              
              </div>
         </div>
              
              <div class="dropdown">
                <div class="dropd">
                <a href="#" class="dropdown-toggle btn btn-default" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                  <i id="greyi" class="fa fa-user" style="font-size:22px"></i>
                          <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                 
                  <li>
                    <a class="drop" href="{%url 'neighbourhood:profile'%}">Profile</a>
                  </li>
                 
                  <li>
                    <a class="drop" href="/accounts/logout">Logout</a>
                  </li>
                </ul>
              </li>
            </div>
           
          </div> 
        
           
    </div>
  </div>
</div>
<div class="center">
  <p>
    Welcome to the Hood and remember,a good neighbour  increases the value of your property
  </p>
</div>
  <div class="container-xl">
    <div class="row">
    <a href="{%  url 'neighbourhood:hood' %}">

      <button type="button" class="btn btn-info">
        Join a Hood 
      </button>
    </a>
    </div>
    
    
      </div>
</div>
  
</div>



    <style>
        *{
           
            padding: 0px;
            margin: 0px;
            color: white;
        }
        .drop{
        color: black;
      }
        .navbar-header a{
        color: white;
        font-size: 25px;
        }
        .enclose{
            display: flex;
            flex-direction: column;
           
        }
        .upper{
          width: 660px;
          height: 40px;
        }
        .card{
            margin: 0px;
            border: none;
            padding-bottom: 0px;
            transition: all .3s;
        }
        .card:hover{
          transform: scale(1.04);
        }
        .glyphicon{
          color: white;
        }
        .backg{
        height: 1100px;
        background-image: url(/media/images/hood1.jpeg);
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
          
        }
        .overlay{
          background: rgb(0, 0, 0, .5);
          height:100vh;
        }
        .post{
        background-color: aqua;
        }

      #search_input{
        background-color: rgb(250, 246, 246);
        border: none;

      }
      #add_input{
        background-color: rgb(248, 248, 248);
        color: rgb(170, 169, 169);
        width: 110px;
        height: 160%;
        /* margin-right: 180px; */
        margin-top: 16px;
      }
     .dropd{
       padding-top: 15px;
       margin-right: 25px;
      color: black;
     }
      .dropd a{
        color: black;
      }
     
      .row button{
        margin-top: 390px;
        margin-left: 430px;
        color: white;
      }
      #greyi{
        color: white;
      }
      .center{
        padding-top: 150px;
        text-align: center;
        color: white;
      }
    </style>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

{% endblock %}